ci:
    # autofix_prs: false
    autoupdate_schedule: quarterly
    skip:
    -   pylint
    -   pytype

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.4
    hooks:
    - id: docformatter
      args: [--in-place, --wrap-summaries=80, --wrap-descriptions=80, --pre-summary-newline]
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
            [
                "-rn", # Only display messages
                "-sn", # Don't display the score
            ]
-   repo: local
    hooks:
    -   id: pytype
        name: pytype
        entry: pytype
        language: system
        types: [python]
        pass_filenames: false
        args: [--config=.pytype.cfg, experiments/]
