name: clean-gitlab

on:
  pull_request:
    types: [closed]

jobs:
  clean-gitlab:
    runs-on: ubuntu-latest
    steps:
    - name: clean-gitlab
      shell: bash
      env:
        GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      run: |
        # remove gitlab branch when pull request is closed
        git init
        git remote add gitlab https://clean-gitlab:$GITLAB_ACCESS_TOKEN@gitlab.mpi-sws.org/simbricks/simbricks.git
        
        # get branch name of pull request from GITHUB_REF, which has the format: refs/pull/<pr_number>/merge
        BRANCH_NAME=${GITHUB_REF##*refs/}
        BRANCH_NAME=${BRANCH_NAME%%/merge*}

        git push gitlab --delete $BRANCH_NAME
